-- Registration Approvals table
CREATE TABLE IF NOT EXISTS registration_approvals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  ticket_class VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reg_approvals_event_status ON registration_approvals(event_id, status);

-- Tickets table (ticket classes)
CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  name VARCHAR(120) NOT NULL,
  group_id VARCHAR(64),
  is_free BOOLEAN NOT NULL DEFAULT FALSE,
  price_in_minor INTEGER NOT NULL DEFAULT 0,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  quantity INTEGER NOT NULL DEFAULT 0,
  sold INTEGER NOT NULL DEFAULT 0,
  requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(24) NOT NULL DEFAULT 'Open',
  sales_start_at TIMESTAMPTZ NULL,
  sales_end_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tickets_event ON tickets(event_id);

-- Payments table
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  ticket_id BIGINT NOT NULL,
  stripe_payment_intent_id VARCHAR(255),
  amount_in_minor INTEGER NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  metadata TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payments_stripe ON payments(stripe_payment_intent_id);

-- Promo codes table
CREATE TABLE IF NOT EXISTS promo_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  code VARCHAR(50) NOT NULL UNIQUE,
  discount_type VARCHAR(20) NOT NULL DEFAULT 'PERCENT',
  discount_amount INTEGER NOT NULL,
  max_uses INTEGER NOT NULL DEFAULT -1,
  used_count INTEGER NOT NULL DEFAULT 0,
  max_uses_per_user INTEGER NOT NULL DEFAULT 1,
  min_order_amount INTEGER NOT NULL DEFAULT 0,
  applicable_ticket_ids TEXT,
  start_date TIMESTAMPTZ,
  end_date TIMESTAMPTZ,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  description VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_promo_codes_event ON promo_codes(event_id);
CREATE INDEX IF NOT EXISTS idx_promo_codes_code ON promo_codes(code);
CREATE INDEX IF NOT EXISTS idx_promo_codes_active ON promo_codes(is_active);

-- Registration Settings table
CREATE TABLE IF NOT EXISTS registration_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL UNIQUE,

  -- Approval Settings
  require_approval BOOLEAN NOT NULL DEFAULT FALSE,
  auto_approve_free_registrations BOOLEAN NOT NULL DEFAULT TRUE,
  require_approval_reason BOOLEAN NOT NULL DEFAULT FALSE,

  -- Email Settings
  send_confirmation_emails BOOLEAN NOT NULL DEFAULT TRUE,
  send_reminder_emails BOOLEAN NOT NULL DEFAULT FALSE,
  reminder_days_before INTEGER NOT NULL DEFAULT 1,
  send_approval_notifications BOOLEAN NOT NULL DEFAULT TRUE,
  send_rejection_notifications BOOLEAN NOT NULL DEFAULT TRUE,

  -- Export & Data Settings
  allow_data_export BOOLEAN NOT NULL DEFAULT TRUE,
  export_includes_personal_data BOOLEAN NOT NULL DEFAULT FALSE,
  require_export_approval BOOLEAN NOT NULL DEFAULT FALSE,
  data_retention_days INTEGER NOT NULL DEFAULT 365,

  -- Registration Flow Settings
  allow_waitlist BOOLEAN NOT NULL DEFAULT TRUE,
  max_waitlist_size INTEGER NOT NULL DEFAULT 100,
  show_remaining_spots BOOLEAN NOT NULL DEFAULT TRUE,
  allow_registration_editing BOOLEAN NOT NULL DEFAULT TRUE,
  registration_deadline_enforced BOOLEAN NOT NULL DEFAULT FALSE,

  -- Security Settings
  require_captcha BOOLEAN NOT NULL DEFAULT FALSE,
  max_registrations_per_ip INTEGER NOT NULL DEFAULT 10,
  registration_rate_limit_minutes INTEGER NOT NULL DEFAULT 15,

  -- Integration Settings
  webhook_url VARCHAR(500),
  webhook_events TEXT,
  enable_analytics_tracking BOOLEAN NOT NULL DEFAULT FALSE,
  google_analytics_id VARCHAR(50),
  facebook_pixel_id VARCHAR(50),

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reg_settings_event ON registration_settings(event_id);

-- Event Attendees table (Missing in initial schema)
CREATE TABLE IF NOT EXISTS event_attendees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255),
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  answers jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_attendees_event ON event_attendees(event_id);

-- Locations table (Missing in initial schema)
CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id VARCHAR(255) UNIQUE,
  name VARCHAR(200) NOT NULL,
  display_name VARCHAR(255),
  address VARCHAR(300),
  city VARCHAR(120),
  state VARCHAR(120),
  country VARCHAR(120),
  lat DOUBLE PRECISION,
  lon DOUBLE PRECISION,
  timezone VARCHAR(64),
  venue_type VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Event Planning table (Missing in initial schema)
CREATE TABLE IF NOT EXISTS event_planning (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL UNIQUE,
  location_id BIGINT,
  budget_inr DOUBLE PRECISION,
  expected_attendees INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Event Registration Settings table (Missing in initial schema)
CREATE TABLE IF NOT EXISTS event_registration_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL UNIQUE,
  is_open BOOLEAN NOT NULL DEFAULT TRUE,
  deadline_at TIMESTAMPTZ,
  capacity INTEGER,
  waitlist_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  require_rsvp BOOLEAN NOT NULL DEFAULT TRUE,
  confirmation_template_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_event_registration_settings_event ON event_registration_settings(event_id);

-- Event RSVPs table (Missing in initial schema)
CREATE TABLE IF NOT EXISTS event_rsvps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  name VARCHAR(100),
  email VARCHAR(150),
  status VARCHAR(16) NOT NULL,
  plus_one INTEGER NOT NULL DEFAULT 0,
  answers_json TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_event_rsvps_event ON event_rsvps(event_id);
CREATE INDEX IF NOT EXISTS idx_event_rsvps_status ON event_rsvps(status);

-- Event Team Members table (Missing in initial schema)
CREATE TABLE IF NOT EXISTS event_team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  role VARCHAR(100) NOT NULL,
  status VARCHAR(32) NOT NULL,
  invited_at TIMESTAMPTZ,
  joined_at TIMESTAMPTZ,
  progress INTEGER
);

CREATE INDEX IF NOT EXISTS idx_event_member_event ON event_team_members(event_id);
CREATE INDEX IF NOT EXISTS idx_event_member_email ON event_team_members(email);
