-- Fix registrations table
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS review_status VARCHAR(50) DEFAULT 'PENDING_APPROVAL';
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS admin_notes TEXT;
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_registrations_email ON registrations(email);
CREATE INDEX IF NOT EXISTS idx_registrations_tenant ON registrations(tenant_id);

-- Fix payments table
ALTER TABLE payments ADD COLUMN IF NOT EXISTS registration_id BIGINT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_details JSONB;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_payments_registration ON payments(registration_id);
CREATE INDEX IF NOT EXISTS idx_payments_user ON payments(user_id);
CREATE INDEX IF NOT EXISTS idx_payments_tenant ON payments(tenant_id);

-- Fix promo_codes table
ALTER TABLE promo_codes ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(255);
CREATE INDEX IF NOT EXISTS idx_promo_codes_tenant ON promo_codes(tenant_id);

-- Create promo_redemptions table
CREATE TABLE IF NOT EXISTS promo_redemptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promo_code_id BIGINT NOT NULL,
  user_id BIGINT,
  order_amount INTEGER,
  discount_amount INTEGER,
  redeemed_at TIMESTAMP DEFAULT NOW(),
  tenant_id VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_promo_redemptions_promo ON promo_redemptions(promo_code_id);
CREATE INDEX IF NOT EXISTS idx_promo_redemptions_user ON promo_redemptions(user_id);
CREATE INDEX IF NOT EXISTS idx_promo_redemptions_tenant ON promo_redemptions(tenant_id);

-- Add registration_approvals if missing (it was used in the code but might not exist)
CREATE TABLE IF NOT EXISTS registration_approvals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  tenant_id VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_registration_approvals_reg ON registration_approvals(registration_id);
CREATE INDEX IF NOT EXISTS idx_registration_approvals_tenant ON registration_approvals(tenant_id);
