-- Create event_invites table
CREATE TABLE IF NOT EXISTS event_invites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  email VARCHAR(255) NOT NULL,
  invitee_name VARCHAR(255),
  organization VARCHAR(255),
  category VARCHAR(255) DEFAULT 'General',
  discount_code VARCHAR(50),
  invite_code VARCHAR(100) NOT NULL,
  invited_by BIGINT,
  invited_at TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP,
  used_at TIMESTAMP,
  registration_id BIGINT,
  status VARCHAR(50) DEFAULT 'PENDING',
  tenant_id VARCHAR(255),
  UNIQUE(event_id, email),
  UNIQUE(invite_code)
);

CREATE INDEX IF NOT EXISTS idx_event_invites_event ON event_invites(event_id);
CREATE INDEX IF NOT EXISTS idx_event_invites_code ON event_invites(invite_code);
CREATE INDEX IF NOT EXISTS idx_event_invites_tenant ON event_invites(tenant_id);
