-- Add check-in fields to registrations table
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS check_in_status VARCHAR(50) DEFAULT 'PENDING';
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS check_in_time TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_registrations_check_in ON registrations(check_in_status);

-- Ensure event_invites table exists (re-run just in case, with IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS event_invites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  email VARCHAR(255) NOT NULL,
  invitee_name VARCHAR(255),
  organization VARCHAR(255),
  category VARCHAR(255) DEFAULT 'General',
  discount_code VARCHAR(50),
  invite_code VARCHAR(100) NOT NULL,
  invited_by BIGINT,
  invited_at TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP,
  used_at TIMESTAMP,
  registration_id BIGINT,
  status VARCHAR(50) DEFAULT 'PENDING',
  tenant_id VARCHAR(255),
  UNIQUE(event_id, email),
  UNIQUE(invite_code)
);
